import { useTranslation } from 'react-i18next';
const en = {
  title: 'Estimated preparation', courseOnlyTitle: 'Preparation in progress', hints: { empty: 'Indicators are being established.', courseOnly: 'Course progress only · Not an overall estimate.', insufficient: 'Insufficient recent evidence for an overall estimate.', available: 'Based on course progress, coverage, recent practice and timed mocks.' }, explain: 'Understand your preparation', close: 'Close', progress: 'View progress',
  method: 'This is a transparent product indicator, not a probability of passing or a guarantee of readiness.', weights: { beginner: 'Early phase: 70% course progression + 30% coverage-weighted practice + 0% timed mocks.', intermediate: 'Intermediate phase: 40% course progression + 40% coverage-weighted practice + 20% timed mocks.', final: 'Final phase: 25% course progression + 40% coverage-weighted practice + 35% timed mocks.' }, courseRule: 'Course progression is the average of completed lessons and completed chapters.', coverageRule: 'Practice accuracy is multiplied by the share of native course concepts assessed. A perfect result on a small sample is not full-program mastery.', capRule: 'The overall indicator is capped at 40% until both course progression and concept coverage reach 50%.', gate: 'A combined number requires course evidence, at least {{concepts}} assessed concepts and—outside the early phase—{{mocks}} recent timed mocks.', missing: 'Missing evidence is not scored as failure. We do not reweight available components to manufacture an overall percentage.', window: 'Practice and mocks use the existing last-30-days selectors. Up to five timed mocks contribute their individual score ratios.', excluded: 'Reading time, audio, bookmarks, streaks and the exam countdown do not increase this indicator.', course: 'Course', lessons: 'Lessons completed', chapters: 'Chapters completed', practice: 'Objective practice', mocks: 'Timed mocks', accuracy: 'Accuracy', coverage: 'Coverage', notAssessed: 'Not assessed', concepts: 'concepts assessed', attempts: 'attempts', latest: 'Latest mock', confidence: 'Confidence: {{value}} ({{concepts}} concepts assessed).', lowConfidence: 'This estimate is provisional: fewer than 50 concepts have been assessed.',
};
const fr: typeof en = {
  title: 'Préparation estimée', courseOnlyTitle: 'Préparation en cours', hints: { empty: 'Indicateurs en cours de création.', courseOnly: 'Progression du cours uniquement · Pas d’estimation globale.', insufficient: 'Données récentes insuffisantes pour une estimation globale.', available: 'Basé sur la progression du cours, la couverture, l’entraînement récent et les examens blancs.' }, explain: 'Comprendre votre préparation', close: 'Fermer', progress: 'Voir les progrès',
  method: 'Cet indicateur de produit n’est pas une probabilité de réussite ni une garantie de préparation.', weights: { beginner: 'Phase débutant : 70 % de progression du cours + 30 % d’entraînement pondéré par la couverture + 0 % d’examens blancs.', intermediate: 'Phase intermédiaire : 40 % de progression du cours + 40 % d’entraînement pondéré par la couverture + 20 % d’examens blancs.', final: 'Phase finale : 25 % de progression du cours + 40 % d’entraînement pondéré par la couverture + 35 % d’examens blancs.' }, courseRule: 'La progression du cours est la moyenne des pourcentages de leçons et de chapitres terminés.', coverageRule: 'La précision d’entraînement est multipliée par la part des concepts natifs du cours qui ont été évalués. Un résultat parfait sur un petit échantillon ne démontre pas la maîtrise du programme.', capRule: 'L’indicateur global est plafonné à 40 % tant que la progression du cours et la couverture des concepts n’atteignent pas toutes deux 50 %.', gate: 'Le nombre global nécessite les données du cours, au moins {{concepts}} concepts évalués et—hors phase débutant—{{mocks}} examens blancs chronométrés récents.', missing: 'Une donnée absente n’est pas un échec. Les composantes disponibles ne sont pas repondérées pour fabriquer un pourcentage global.', window: 'L’entraînement et les examens utilisent les sélecteurs existants sur 30 jours. Jusqu’à cinq examens blancs contribuent avec leurs résultats proportionnels.', excluded: 'Le temps de lecture, l’audio, les favoris, les séries et le compte à rebours de l’examen n’augmentent pas cet indicateur.', course: 'Cours', lessons: 'Leçons terminées', chapters: 'Chapitres terminés', practice: 'Entraînement objectif', mocks: 'Examens blancs chronométrés', accuracy: 'Précision', coverage: 'Couverture', notAssessed: 'Pas encore évalué', concepts: 'concepts évalués', attempts: 'tentatives', latest: 'Dernier examen blanc', confidence: 'Indice de confiance : {{value}} ({{concepts}} concepts évalués).', lowConfidence: 'Cette estimation reste provisoire : moins de 50 concepts ont été évalués.',
};
export function usePreparationText(): typeof en { const { i18n } = useTranslation(); return i18n.language.startsWith('fr') ? fr : en; }
