export const reminderCopyEn = {
  title: `Citizenship preparation`,
  taskTitles: { exam: [`Your exam is waiting`, `Ready to continue your timed exam?`, `Pick up your exam when you're ready`], review: [`A focused review is ready`, `Keep your concepts fresh`, `A short review can make a difference`], chapter: [`A chapter is ready to validate`, `Turn completed lessons into a validated chapter`, `Your next chapter milestone is ready`], lesson: [`Your next study step is ready`, `Continue where you left off`, `A focused lesson is waiting`], study: [`A small study step is waiting`, `Keep your preparation moving`, `Ready for a focused session?`] },
  taskBodies: { exam: [`Your timed exam is still in progress. Resume when you are ready.`, `Your answers are saved. Continue the exam at your own pace.`, `Return to your active exam and finish when it suits you.`], review: [`{{count}} concept(s) are due for review. Start with a focused session.`, `Review {{count}} due concept(s) and keep them active.`, `Your review queue has {{count}} concept(s) ready when you are.`], chapter: [`{{chapter}} has completed lessons. Take the chapter quiz when you feel ready.`, `You finished the lessons in {{chapter}}. Validate the chapter with its quiz.`, `Your next milestone is {{chapter}}. Its chapter quiz is ready.`], lesson: [`Continue “{{lesson}}” — your place is saved.`, `A short session on “{{lesson}}” keeps your course moving.`, `Return to “{{lesson}}” whenever you have a focused moment.`], study: [`Choose one short step: a lesson, a review or a practice exam.`, `A focused session today keeps your preparation moving.`, `Open the app when you are ready for your next study step.`] },
  examSoonTitles: [`Your exam is getting closer`, `A useful check-in before your exam`, `Prepare your pace for exam day`],
  examSoonBodies: [`Your exam date is in {{days}} day(s). A timed mock can help you practise pace.`, `With {{days}} day(s) left, choose one focused review or mock exam.`, `Your exam is in {{days}} day(s). Keep the next session short and useful.`],
};
export const reminderCopyFr: typeof reminderCopyEn = {
  title: `Préparation à la citoyenneté`,
  taskTitles: { exam: [`Votre examen vous attend`, `Prêt à reprendre votre examen chronométré ?`, `Reprenez votre examen quand vous le souhaitez`], review: [`Une révision ciblée est prête`, `Gardez vos concepts actifs`, `Une courte révision peut être utile`], chapter: [`Un chapitre est prêt à être validé`, `Transformez les leçons terminées en chapitre validé`, `Votre prochain jalon est prêt`], lesson: [`Votre prochaine étape d’étude est prête`, `Reprenez là où vous vous êtes arrêté`, `Une leçon ciblée vous attend`], study: [`Une petite étape d’étude vous attend`, `Faites avancer votre préparation`, `Prêt pour une session ciblée ?`] },
  taskBodies: { exam: [`Votre examen chronométré est toujours en cours. Reprenez-le quand vous êtes prêt.`, `Vos réponses sont enregistrées. Continuez l’examen à votre rythme.`, `Retournez à votre examen en cours et terminez quand cela vous convient.`], review: [`{{count}} concept(s) sont à réviser. Commencez par une session ciblée.`, `Révisez {{count}} concept(s) à revoir et gardez-les actifs.`, `Votre file de révision contient {{count}} concept(s) prêts quand vous l’êtes.`], chapter: [`Les leçons de « {{chapter}} » sont terminées. Passez le quiz du chapitre quand vous vous sentez prêt.`, `Vous avez terminé les leçons de « {{chapter}} ». Validez le chapitre avec son quiz.`, `Votre prochain jalon est « {{chapter}} ». Son quiz est prêt.`], lesson: [`Continuez « {{lesson}} » — votre place est enregistrée.`, `Une courte session sur « {{lesson}} » fait avancer votre cours.`, `Reprenez « {{lesson}} » quand vous avez un moment ciblé.`], study: [`Choisissez une courte étape : une leçon, une révision ou un examen d’entraînement.`, `Une session ciblée aujourd’hui fait avancer votre préparation.`, `Ouvrez l’application lorsque vous êtes prêt pour votre prochaine étape.`] },
  examSoonTitles: [`Votre examen approche`, `Un point utile avant votre examen`, `Préparez votre rythme pour le jour de l’examen`],
  examSoonBodies: [`Votre date d’examen est dans {{days}} jour(s). Un examen blanc chronométré peut vous aider à travailler le rythme.`, `Il reste {{days}} jour(s) : choisissez une révision ciblée ou un examen blanc.`, `Votre examen est dans {{days}} jour(s). Gardez votre prochaine session courte et utile.`],
};
export function reminderCopy(language: string) { return language.startsWith('fr') ? reminderCopyFr : reminderCopyEn; }
