export const reminderCopyEn = {
  title: `Citizenship preparation`,
  taskTitles: { exam: [`⏱ Timed exam in progress`, `Return before the timer ends`, `Your exam answers are saved`], review: [`🔄 A focused review is ready`, `Keep your concepts fresh`, `A short review can make a difference`], chapter: [`🏆 A chapter is ready to validate`, `Your next chapter milestone is ready`, `Finish a chapter with its quiz`], lesson: [`📚 Your next study step is ready`, `Make room for a focused lesson`, `Keep your course moving`], study: [`A focused practice step is waiting`, `Keep your preparation moving`, `Ready for a mock exam?`] },
  taskBodies: { exam: [`The timer keeps running. Open the app to resume if time remains.`, `Your answers are saved. Resume while the timer is running.`, `Tap to check the remaining time in your active attempt.`], review: [`A review session is ready. Tap to see what is due now.`, `Give your concepts a fresh retrieval check. Open your review queue.`, `Make your next step a focused review. The app will show the current queue.`], chapter: [`The lessons in “{{chapter}}” are complete. Take its chapter quiz when ready.`, `Validate “{{chapter}}” with a focused chapter quiz.`, `Your next milestone is “{{chapter}}”. Tap to open its quiz page.`], lesson: [`Continue “{{lesson}}” with one focused step.`, `If you have {{minutes}} minutes, spend them on “{{lesson}}”.`, `Return to “{{lesson}}” whenever you have a focused moment.`], study: [`Try one mock exam when you are ready for timed practice.`, `Choose a practice exam and check your pace.`, `A mock exam is a useful next step. Tap to choose one.`] },
  examSoonTitles: [`📅 Your exam check-in`, `A useful check-in before your exam`, `Prepare your pace for exam day`],
  examSoonBodies: [`Your scheduled {{days}}-day preparation check-in. Try a timed mock when ready.`, `For this {{days}}-day milestone, choose one focused review or mock exam.`, `Your {{days}}-day check-in is here. Open the app for the current exam countdown.`],
};
export const reminderCopyFr: typeof reminderCopyEn = {
  title: `Préparation à la citoyenneté`,
  taskTitles: { exam: [`⏱ Examen chronométré en cours`, `Revenez avant la fin du minuteur`, `Vos réponses d’examen sont enregistrées`], review: [`🔄 Une révision ciblée est prête`, `Gardez vos concepts actifs`, `Une courte révision peut être utile`], chapter: [`🏆 Un chapitre est prêt à être validé`, `Votre prochain jalon est prêt`, `Terminez un chapitre avec son quiz`], lesson: [`📚 Votre prochaine étape d’étude est prête`, `Accordez-vous une leçon ciblée`, `Faites avancer votre cours`], study: [`Une étape d’entraînement ciblée vous attend`, `Faites avancer votre préparation`, `Prêt pour un examen blanc ?`] },
  taskBodies: { exam: [`Le minuteur continue. Ouvrez l’application pour reprendre s’il reste du temps.`, `Vos réponses sont enregistrées. Reprenez pendant que le minuteur fonctionne.`, `Touchez pour vérifier le temps restant de votre tentative en cours.`], review: [`Une session de révision est prête. Touchez pour voir les concepts à revoir maintenant.`, `Vérifiez à nouveau le rappel de vos concepts. Ouvrez votre file de révision.`, `Choisissez une révision ciblée. L’application affichera la file actuelle.`], chapter: [`Les leçons de « {{chapter}} » sont terminées. Passez son quiz quand vous êtes prêt.`, `Validez « {{chapter}} » avec un quiz ciblé.`, `Votre prochain jalon est « {{chapter}} ». Touchez pour ouvrir la page du quiz.`], lesson: [`Continuez « {{lesson}} » avec une étape ciblée.`, `Si vous avez {{minutes}} minutes, consacrez-les à « {{lesson}} ».`, `Reprenez « {{lesson}} » quand vous avez un moment ciblé.`], study: [`Essayez un examen blanc quand vous êtes prêt pour un entraînement chronométré.`, `Choisissez un examen d’entraînement et vérifiez votre rythme.`, `Un examen blanc est une prochaine étape utile. Touchez pour en choisir un.`] },
  examSoonTitles: [`📅 Votre point avant l’examen`, `Un point utile avant votre examen`, `Préparez votre rythme pour le jour de l’examen`],
  examSoonBodies: [`Votre point de préparation prévu à {{days}} jours. Essayez un examen blanc quand vous êtes prêt.`, `Pour ce jalon de {{days}} jours, choisissez une révision ciblée ou un examen blanc.`, `Votre point de préparation de {{days}} jours est arrivé. Ouvrez l’application pour le compte à rebours actuel.`],
};
export function reminderCopy(language: string) { return language.startsWith('fr') ? reminderCopyFr : reminderCopyEn; }
