export const uiEn = {
  quiz: { correct: `Correct!`, incorrect: `Not quite`, scoreSoFar: `{{count}} correct`, tierHigh: `Excellent work!`, tierMid: `Good progress, keep going.`, tierLow: `Review the lesson and try again.`, correctLabel: `Correct`, missedLabel: `Missed` },
  learnUi: { chapter: `Chapter {{n}}`, overall: `Overall progress`, startChapter: `Start chapter`, continueChapter: `Continue chapter`, reviewChapter: `Review chapter`, lessonCount_one: `{{count}} lesson`, lessonCount_other: `{{count}} lessons`, quizCount: `{{count}} questions` },
  studyControls: { chooseAnswer: `Choose an answer to continue.`, results: `View results` },
  bookmarksUi: { title: `Bookmarks`, save: `Bookmark`, saved: `Saved`, remove: `Remove bookmark`, hint: `Saved questions for later practice. Bookmarks are separate from exam flags.`, search: `Search saved questions…`, count_one: `{{count}} saved question`, count_other: `{{count}} saved questions`, empty: `No bookmarks yet. Use Bookmark on a question to save it.`, practice: `Practise saved questions`, practiceOne: `Practise this question`, recorded: `Your grade is saved. Continue to the next card.` },
};
export const uiFr: typeof uiEn = {
  quiz: { correct: `Bonne réponse !`, incorrect: `Pas tout à fait`, scoreSoFar: `{{count}} bonnes`, tierHigh: `Excellent travail !`, tierMid: `Bonne progression, continuez !`, tierLow: `Relisez la leçon et réessayez.`, correctLabel: `Réussies`, missedLabel: `Ratées` },
  learnUi: { chapter: `Chapitre {{n}}`, overall: `Progression globale`, startChapter: `Commencer le chapitre`, continueChapter: `Continuer le chapitre`, reviewChapter: `Revoir le chapitre`, lessonCount_one: `{{count}} leçon`, lessonCount_other: `{{count}} leçons`, quizCount: `{{count}} questions` },
  studyControls: { chooseAnswer: `Choisissez une réponse pour continuer.`, results: `Voir les résultats` },
  bookmarksUi: { title: `Signets`, save: `Ajouter un signet`, saved: `Enregistré`, remove: `Retirer le signet`, hint: `Questions enregistrées pour vous entraîner plus tard. Les signets sont distincts des marques d'examen.`, search: `Rechercher une question enregistrée…`, count_one: `{{count}} question enregistrée`, count_other: `{{count}} questions enregistrées`, empty: `Aucun signet. Ajoutez un signet sur une question pour l'enregistrer.`, practice: `S'entraîner avec les signets`, practiceOne: `S'entraîner sur cette question`, recorded: `Votre évaluation est enregistrée. Passez à la carte suivante.` },
};
