import { describe, expect, test } from '@jest/globals';
import { makeBundle } from '../test-utils/fixtures';
import { initialLearning } from './completion';
import { snapshot } from './dashboardStats';
import { initialAssessmentHistory, type ExamEvidence } from './learningStats';
import { preparationEstimate, preparationPhase } from './preparation';
const bundle = makeBundle(); const now = new Date(2026, 9, 3, 12).getTime();
const empty = snapshot(bundle, { ...initialLearning(), ...initialAssessmentHistory(), attempts: [], cards: {}, active: null }, now);
const mock = (id: string, correct = 15, at = now): ExamEvidence => ({ attempt: { id, examId: bundle.exams[0].id, lang: bundle.lang, seed: 1, questionIds: [], startedAt: at - 1000, finishedAt: at, limitMs: 60000, answers: [] }, correct, total: 20, answered: 20, required: 15, passed: correct >= 15, ratio: correct / 20 });
const evidence = (concepts: number, pool = 100, correct = concepts, total = concepts) => ({ ...empty.evidence, coverage: { correct: concepts, total: concepts, accuracy: concepts ? correct / total : null, distinctConcepts: concepts, assessableConcepts: pool, coverage: pool ? concepts / pool : null }, practice: { correct, total, distinctConcepts: total, accuracy: total ? correct / total : null } });
const data = (course = 0.5, concepts = 60, accuracy = 1, mocks: ExamEvidence[] = [mock('a'), mock('b')], pool = 100) => ({ ...empty, completion: { ...empty.completion, lessonsCompleted: Math.round(course * 10), lessonsTotal: 10, chaptersCompleted: Math.round(course * 10), chaptersTotal: 10 }, evidence: evidence(concepts, pool, Math.round(concepts * accuracy), concepts), exams: { ...empty.exams, recentMocks: mocks } });
describe('coverage-weighted preparation indicator', () => {
  test('weights training accuracy by native concept coverage', () => { const value = preparationEstimate(data(0.8, 38, 1), now); expect(value.practiceAccuracyPercent).toBe(100); expect(value.coveragePercent).toBe(38); expect(value.practicePercent).toBeCloseTo(38); });
  test('caps a high score at 40 when course progress is below half', () => { const value = preparationEstimate(data(0.2, 100, 1), now); expect(value.rawPercent).toBeCloseTo(44); expect(value.capped).toBe(true); expect(value.percent).toBe(40); });
  test('caps a high score at 40 when concept coverage is below half', () => { const value = preparationEstimate(data(0.8, 38, 1), now); expect(value.capped).toBe(true); expect(value.percent).toBeLessThanOrEqual(40); });
  test('uses phase weights at both boundaries', () => { expect(preparationPhase(0.29)).toBe('beginner'); expect(preparationPhase(0.3)).toBe('intermediate'); expect(preparationPhase(0.7)).toBe('intermediate'); expect(preparationPhase(0.71)).toBe('final'); });
  test('beginner phase does not require a mock and prioritizes course work', () => { const value = preparationEstimate(data(0.2, 100, 1, []), now); expect(value.state).toBe('available'); expect(value.weights).toEqual({ course: 0.7, practice: 0.3, mocks: 0 }); expect(value.percent).toBe(40); });
  test('intermediate and final phases require timed mock evidence', () => { expect(preparationEstimate(data(0.5, 100, 1, []), now).percent).toBeNull(); expect(preparationEstimate(data(0.8, 100, 1, []), now).percent).toBeNull(); });
  test('confidence uses assessed concepts and is capped at 100 percent', () => { expect(preparationEstimate(data(0.8, 38), now).confidence).toBeCloseTo(0.38); expect(preparationEstimate(data(0.8, 150, 1, [mock('a'), mock('b')], 200), now).confidence).toBe(1); });
  test('empty evidence remains a dash rather than a readiness score', () => { expect(preparationEstimate(empty, now)).toMatchObject({ state: 'empty', percent: null, confidence: 0 }); });
  test('course-only activity remains separate from the overall estimate', () => { const value = preparationEstimate({ ...empty, completion: data(0.5).completion }, now); expect(value).toMatchObject({ state: 'courseOnly', percent: null }); });
});
